### ISSUE TITLE
[question] Any support for ES6 classe

### ISSUE THREAD

**Issue by ieugen** [insin/newforms#107]
Hi, 

I was wondering if you have support for EcmaScript 6 classes. 

Like:

```
class MyForm extends forms.Form {
// fields here and handlers
}
```

**Comment by insin** [comment]
ES6 classes aren't supported as - being sugar for regular prototype inheritance - they don't have any extension-time hooks for customising the prototype of the resulting constructor.

Newforms needs a hook like this to do [some work](https://github.com/insin/newforms/blob/react/src/forms/DeclarativeFieldsMeta.js) when you're extending a form.
