### ISSUE TITLE
custom validator messages are broken

### ISSUE THREAD

**Issue by kamholz** [insin/newforms#11]
I created a custom validator like this:

var validateUsername = new forms.RegexValidator(/^[a-zA-Z_.-]+$/,
    'must contain only letters, numbers, -, _ or .');

However, the custom validation message is not actually applied when the validator generates an error. Instead I get the default "invalid" error message. I can solve this by doing the following in the form constructor:

```
username:   forms.CharField({maxLength: 255, validators: [validateUsername],
    errorMessages: { invalid: validateUsername.message } }),
```

But it seems like this should not be necessary and is probably a bug.

**Comment by insin** [comment]
Looks like an issue with how fields use ValidationErrors thrown from their `validators` list - they look in the field's own default error messages first any time the ValidationError has a `code`, which it always will with validators.
