### ISSUE TITLE
How to build project from source for NPM? 

### ISSUE THREAD

**Issue by laszbalo** [insin/newforms#125]
I think I have found a bug in FormSet#addAnother(). I am planning to raise a separate issue for it, but first I'd like to know if there is any script that I can use to create a folder structure that I can get when I require newforms form NPM.

After cloned the repo and ran 'npm run dist', it creates two bundles(minified and normal). When I look at the ./node_modules/newforms though, it seems, it contains the un-bundled version.(multiple separate files)

With thanks,
Laszlo

**Comment by insin** [comment]
`npm run npm` should generate an `npm-newforms` directory, which is what gets published to npm.

**Comment by laszbalo** [comment]
Thanks,

I somehow missed it...
