### ISSUE TITLE
Can not override defaultValidators

### ISSUE THREAD

**Issue by ngonhan2k5** [insin/newforms#134]
Is there any others way without modify the package?
I have to modify Fields.js: 
```
    //this.validators = this.defaultValidators.concat(kwargs.validators)
    this.validators = kwargs.validators || this.this.defaultValidators
```
then I can:

```
const LoginForm = forms.Form.extend({
    email: forms.EmailField({validators: [EmailValidator({message:'my customize email invalid msg'})] }),
    password: forms.CharField({widget: forms.PasswordInput})
  }
)
```
to override default message

commit: https://github.com/insin/newforms/pull/135/commits/ef2b4cc8855eae312f385a7840afb3e3fa16894b
pull: https://github.com/insin/newforms/pull/135

**Comment by insin** [comment]
Does the [`errorMessages`](http://newforms.readthedocs.io/en/latest/fields.html#errormessages) argument allow you to do what you need to?

Error message codes for `EmailField` are here: http://newforms.readthedocs.io/en/latest/fields.html#emailfield
Example from tests: https://github.com/insin/newforms/blob/85e7dc4723c78f213ee31d081ede534212352060/tests/errormessages.js#L108

**Comment by ngonhan2k5** [comment]
Oh so the errorMessage's codes made it.
Thank you very much.
