### ISSUE TITLE
initial option not working for choice fields

### ISSUE THREAD

**Issue by AndrewIngram** [insin/newforms#45]
I have many choicefields and typedchoicefields that have initial values set, but they're not being pre-selected when the form renders.

```
timezone: forms.ChoiceField({
  choices: TIMEZONE_CHOICES,
  initial: '+0000',  // '+0000' is definitely one of the choices
  label: 'Your timezone'
})
```

**Comment by insin** [comment]
Fixed in 0.5.2.

Unit testing against string output won't catch these sort of misses - need to add DOM-based tests for 0.6's interactive validation, so will add this as a regression then.
