### ISSUE TITLE
Uncaught Error: formData was given form=undefined

### ISSUE THREAD

**Issue by kevzettler** [insin/newforms#48]
I'm getting this error from a custom form and not sure what i'm missing. This form also uses some custom widgets and i'm not sure how to implement them to pass the data back to the form object. 

Heres the root form:

https://gist.github.com/kevzettler/6ed9a042a670a35298ff

**Comment by insin** [comment]
Your `<form>` has `ref="profileForm"` - try passing `this.refs.profileForm` instead.

Widgets don't pass data  back to the form object - their current value is retrieved from their real DOM representation via `event.target`  during an `onChange` or from the real DOM `<form>` when passed to `form.validate()`. There's an example of extending a `MultiWidget` in the unit tests, but the only reference for creating custom `Widgets` at the moment is the [`widgets.js`](https://github.com/insin/newforms/blob/react/lib/widgets.js) source code.

What does your `NFLabelWidget` look like? You shouldn't need to pass it the field name it's assigned to in the form, as this is passed as an argument to its [`render()`](http://newforms.readthedocs.org/en/latest/widgets_api.html#Widget#render) method:by its `BoundField` when rendering.

**Comment by kevzettler** [comment]
Where am I supposed to pass `this.refs.profileForm` to?

`NFLabelWidget` is a little complicated. I have a bunch of preexisting standar React components for form inputs that I am wrapping in a helper function to convert them into `newforms.Widget` style you can see here:

https://gist.github.com/kevzettler/c7522e807e00e7cd8721

so I'm passing it field name and other stuff to the underlying React component props but that can be refactored.

**Comment by insin** [comment]
To `if (form.validate(this.refs.profileForm)) { ... }`

A Widget in newforms only handles generating ReactElements for the actual input the user interacts with - it's not a React component itself.

When you do `var fields = form.boundFieldsObj()` you're creating a bunch of  `BoundField` objects which grab all the data a Widget needs to render and pass it to the Widget's `render()` method, so this approach won't work. Here's a more canonical way to get similar output:

Fields already have a `label` property that's used by BoundFields when generating a label tag for you (with all the right ids and whatnot hooked up): If you just need to add a placeholder to a regular `<input>`, you can do it like this:

``` javascript
fname: newforms.CharField({
  label: 'First Name',
  widget: newforms.TextInput({attrs: {placeholder: 'John'}})
})
```

Then in your component's `render()`, you could use [what BoundField already gives you](http://newforms.readthedocs.org/en/latest/overview.html#customising-form-display) to render the `<label>`:

``` html
<div className="pure-u-1 pure-u-md-1-2">
  {fields.fname.labelTag()}
  {fields.fname.render()}
  {fields.fname.errors().render()}
</div>
```

You could further pull this out into a reusable function which takes the className and BoundField, or a custom React component which does the same.

**Comment by kevzettler** [comment]
Thanks for all the help @insin

**Comment by kevzettler** [comment]
@insin any way to add an html class to the `<label>` in that example?

**Comment by insin** [comment]
http://newforms.readthedocs.org/en/latest/forms_api.html#BoundField#labelTag

This should do it:

``` javascript
{fields.fname.labelTag({attrs: {className: 'whatever'}})}
```
