### ISSUE TITLE
Best way to show success message?

### ISSUE THREAD

**Issue by kevzettler** [insin/newforms#49]
Are there any hooks for putting in in a submission success message? whats the recommended practice here?

**Comment by insin** [comment]
That's outside the scope of newforms, really. It hands you a boolean `isValid` value, gently places its `cleanedData` on the ground and backs away slowly :smile:

The simplest way to do this in React is to have a bit of state which tracks success or failure of submission and is used when rendering to indicate to the user what's happened. It depends entirely on what you need to do here, though, and how your app is set up.
