### ISSUE TITLE
Add `react-component` keyword to package.json

### ISSUE THREAD

**Issue by gcanti** [insin/newforms#50]
In order to allow react-component to find newforms

http://react-components.com/search/newforms

Example:

https://github.com/gcanti/tcomb-form/blob/master/package.json#L40

**Comment by insin** [comment]
I might hold off on this until newforms actually has some components or mixins - it already seems to be confusing enough based on questions/feedback from some people who've tried it.

At the moment, the rendering side is more like helper objects and the form/field metadata side is plain old JavaScript objects.

**Comment by gcanti** [comment]
I see, I just wanted to be sure you knew that opportunity ;-)
