### ISSUE TITLE
error state on inputs

### ISSUE THREAD

**Issue by kevzettler** [insin/newforms#51]
Is there any way to apply a class to the inputs on validation error state?

**Comment by insin** [comment]
If you give ypur Form definition an [errorCssClass](http://newforms.readthedocs.org/en/v0.8.0/forms.html#styling-form-rows) property it'll be applied to invalid field rows by default rendering, or available via a BoundField's [cssClasses()](http://newforms.readthedocs.org/en/v0.8.0/forms_api.html#BoundField#cssClasses) if irs field is invalid.

There's an example of the latter in the custom layouts example: https://github.com/insin/newforms-examples/blob/master/custom-layout/app.jsx

**Comment by kevzettler** [comment]
How does this work if i'm manually rendering the fields with `{fields.fieldname.render()}` and not using the "form row" concept?

**Comment by insin** [comment]
You can pass an object with an attrs object into the render call: http://newforms.readthedocs.org/en/v0.8.0/forms_api.html#BoundField#render

Example of doing that with a title attribute here: https://github.com/insin/dinnertime/blob/master/src/Planner.jsx
