### ISSUE TITLE
newforms.Form.extend mutates Field object breaks re-rendering of form.

### ISSUE THREAD

**Issue by kevzettler** [insin/newforms#54]
I"m trying to dynamically include Fields from a separate file to pass to `Form.extend`. On the initial render of the form everything is cool. Subsequent renders of the form break because the fields object has been mutated and instead of an `Object` i'm passing in a `childConstructor` to `Form.extend`.

``` javascript
Object {US: Object, CA: Object}
```

```
var Fields = require("./fields"),
      BankForm = newforms.Form.extend(Fields[country]);
```

``` javascript
Object {US: childConstructor, CA: Object}
```

**Comment by insin** [comment]
This should be fixed by v0.9.1:

https://github.com/insin/newforms/releases/tag/v0.9.1
