### ISSUE TITLE
How do you design for and implement isomorphic form submission?

### ISSUE THREAD

**Issue by insin** [insin/newforms#55]
## Use case

You want to support using part or all of your React app when JavaScript is disabled or otherwise unavailable (e.g. flaky connections, slow connection, ISP script injection breaking your JavaScript).

---
### What newforms gives you
- User inputs are given unique `name` attributes, so they'll count as successful form controls if a regular form submission is allowed to happen.
- When JavaScript is available on the client, `form.data` is kept up to date for you, and matches what you would get from a form submission HTTP request after it had been parsed by the likes of [expressjs/body-parser](https://github.com/expressjs/body-parser)
- The Widget which was used to render the user input(s) for a Field is also used to extract input data from `form.data`; Widgets are aware of the fiddly details of HTTP form submission and whether or not a single value or a list is expected.
- This allows you to use the same Forms/FormSets on client and server to ultimately get the same `cleanedData`.

---

The question is, how do you design for and implement performing the action that's taken with the validated data on both client and server?

The first obvious step is that when you want to support using part or all of your React app as a forms 'n links webapp, you need to give your `<form>` elements an appropriate `action` and `method`:

``` html
<form action="/addthing" method="POST">
  <forms.RenderForm form={ThingForm} ref="form"/>
  <button>Submit</button>
</form>
```

But what does the submit handling required look like on both sides?

(Speculative code below. Also making too many assumptions below to list them!)
### Client

``` javascript
onSubmit(e) {
  e.preventDefault()
  var form = this.refs.form.getForm()
  if (form.validate()) {
    ThingService.addThing(form.cleanedData, (err, payload) => {
      // Set error state, or add errors to form, or navigate away, or set success state
    })
  }
}
```
### Server

``` javascript
app.get('/addthing', (req, res) => {
  var form = new ThingForm()
  // Respond with React-rendered HTML
})

app.post('/addthing', (req, res) => {
  var form = new ThingForm({data: req.body})
  function redisplay(err) {
    // If this was an XMLHttpRequest, respond with a 403 and error or validation error payload
    // If this was a regular form submission, respond with React-rendered HTML using form and err
  }
  if (form.isValid()) {
    return ThingStorage.addThing(form.cleanedData, (err, newThing) => {
      if (err) { return redisplay(err) }
      // If this was an XMLHttpRequest, respond with a 200 and any payload required
      // If this was a regular form submission, redirect to the appropriate URL
    })
  }
  // Fall through to redisplay errors
  redisplay()
})
```

Does this actually work for starters?
Should express-like handlers be the starting point, or something like react-router's `Router.run()`, which gives you a list of matched routes and their React component handlers?
Are there pieces which should be shared via static functions on the React component?

**Comment by insin** [comment]
I now have the following working isomorphically with [React Router](https://github.com/rackt/react-router) and [express](https://github.com/strongloop/express) in [this component](https://github.com/insin/isomorphic-lab/blob/master/src/components/AddThing.jsx), with plenty of reference to the [React Router Mega Demo](https://github.com/rackt/react-router-mega-demo):
- Initial form display
- Form submission and redisplay with user input and form validation errors (using an HTTP round-trip if JavaScript isn't available)
- Redisplay with external validation errors (e.g server-only validation)
- Redirect-after-POST.

It works with JavaScript turned off, entirely using HTTP round trips, server-side processing and rendering.

If JavaScript is available at any point, React will hook up events and take over routing, data fetching and rendering.

## Request processing

The general idea is that you use react-router's `willTransitionTo(transition, params, query)` hook on route handler components to do request processing work.

`transition.wait(promise)` lets you have the pending transition wait while you do async stuff. For a form submission, this is making whatever changes need to be made: adding, updating, deleting, yada yada yada...

The query parameter is currently the only easy way I've seen to get request-specific, one-time data in here - this was also @rpflorence's [recommended approach](https://twitter.com/ryanflorence/status/545265219316879362).

## POSTing data

So how do you do an isomorphic HTTP POST?

**Sever-side:** a real HTTP POST will have happened via the `<form>`, the incoming request's form parameters will have been parsed into `req.body`
**Client-side:** pre-validated input data is in a Form instance's `data` object.

What's common?
- They need to get data into `willTransitionTo()` via its `query` parameter, and `willTransitionTo()` should only do its work on POST.
- `form.data` is purposefully kept compatible with what will be submitted via a regular form submission, so it and `req.body` are actually equivalent!

In both cases, we need to do the same thing in order to get data into `query` - craft a URL with a query string containing user input. On the server side, a new `Router` is created with a static location to handle each request, so we can tweak the URL which will be given to it:

``` javascript
var url = req.url
if (req.method == 'POST') {
  url += `?_method=${req.method}&${querystring.stringify(req.body)}`
}
```

The user never sees this modified URL, so it's all good.

On the client side, a Router is already in place, so we can use the `Navigation` mixin to do the work:

``` javascript
this.transitionTo('/addthing', {}, assign({_method: 'POST'}, form.data))
```

> It looks like the URL is displayed in the address bar before a transition finishes, which isn't ideal, as the user will see it until the relevant `willTransitionTo` is finished doing its work.

In both cases, we've added a `_method` parameter to indicate that we're doing a POST, as a convenient way to determine if we need to do anything in `willTransitionTo`:

``` javascript
willTransitionTo(transition, params, query) {
  if (query._method != 'POST') { return }
```

The reason I used the same component to display and process the form is...

## Redisplay

Redisplaying a form with its original user input plus validation errors is where things start to diverge.

**Sever-side:** do a complete re-render with user input and validation errors.
**Client-side:** update the existing form's state with validation errors to be displayed.

> Aside:This is potentially a good argument for keeping form state somewhere external to be passed in as props...

POST processing is happening as a result of a transition to `/addthing` with certain query parameters. **Ideally, we could just configure props to be passed to the router handler when it's being rendered and let the transition continue**, but I can't see any way to allow the transition to complete **and** pass some data back, so instead we use `transition.abort()` to cancel the pending transition. This method takes a `reason` parameter which we use on the server side to handle special types of responses, such as redirects.

> Protip: `transition.redirect(...)` is just sugar for `transition.abort(new Redirect(...))`

This is where the logic currently branches if we call the API to save the new data and get validation errors back:

``` javascript
if (env.CLIENT) {
  // Update the form with validation errors received from the API
  events.emit(AddThing.ERRORS_EVENT, ErrorObject.fromJSON(res.body))
  transition.abort()
}
else {
  // Re-render with user input + validation errors from the API
  transition.abort(new Render('/addthing', {
    initialData: query
  , initialErrors: res.body
  }))
}
```

The client side is using an `EventEmitter` to send the validation errors directly to the form component which is currently mounted and registered for a component-specific event.

The server side is using abort's `reason` parameter to pass back a URL and some props in an identifiable wrapper object - this ultimately ends up triggering a new render (with a new Router) which gets those props passed to the handler rendered for it.

These are both hacks, really, and both to avoid just redirecting with everything they need to pass serialised on a query string. I'm ok with the form-POST-to-query-parameter hack, as that's the way form data is submitted anyway, but it _feels_ wrong to abuse it for structured data like validation errors. It would probably eliminate the need for branching here, but my biggest problem with it would be the resulting URLs on the client side, reflecting the user's input back at them again.

> TODO: currently only the server side has a custom `onAbort` to handle what's coming out of `willTransitionTo` - could the `Render` solution also work on the client side if one was implemented there?

## Redirect-after-POST

AKA The Very Easy Bit

```
if (res.ok) {
  transition.redirect('/things')
}
```

**Comment by ryanflorence** [comment]
I've been thinking about the POST use case. I've thought about branching for server v. client:

**Server**

Simply add `method="POST"` to the form, process data from `req.body` if `ENV.SERVER`. Its not clear how to get the `req` to `willTransitionTo` of a route handler, but a little [application container](http://github.com/rpflorence/create-container) would work.

**Client**

Put `POST` data in a temporary variable (`window.__POST_DATA__` for a quick implementation), read from it `if (ENV.CLIENT)`.
