### ISSUE TITLE
DecimalField validation turns '0' into empty string

### ISSUE THREAD

**Issue by MattFisher** [insin/newforms#57]
The line `value = value.replace(/^0+/, '')` at https://github.com/insin/newforms/blob/react/lib/fields.js#L440 within `DecimalField.prototype.clean` turns the string "0" into "", which is later returned for storage in cleaned_data.

It is also fed into `this.runValidators(parseFloat(value))` at https://github.com/insin/newforms/blob/react/lib/fields.js#L482, and I haven't checked whether it will validate if max and min values have been set.

A simple but slightly hacky solution would be:

```
if (value !== '0') {
    value = value.replace(/^0+/, '')
}
```

**Comment by insin** [comment]
Thanks for the bug report, a proper native decimal type can't come too soon :grin:
