### ISSUE TITLE
Error messages not being interpolated

### ISSUE THREAD

**Issue by kevzettler** [insin/newforms#58]
Using a custom widget with `IntegerField` i'm seeing un-interpolated error messages
![screenshot 2015-02-18 18 30 26](https://cloud.githubusercontent.com/assets/126209/6260992/8d3ca664-b79c-11e4-9f52-5a4c2518f955.png)

``` javascript
var quantityForm = newforms.Form.extend({
                quantity: forms.IntegerField({
                    name: 'quantity',
                    maxValue: 6,
                    widget: Form.NFQuantitySelector({
                        defaultValue: 5
                    })
                }),
            });
```

I'm doing some custom error output that looks like :

``` javascript
                errs.errors[field_id].data.forEach(function(err_obj){
                    var message = '';
                    if(label != null){
                        message += label + ". ";
                    }
                    message += err_obj.message;
                    err_messages.push(message);
```

I guess I need to manually do the interpolation here? can you point me to where thats done within newforms?

**Comment by insin** [comment]
[Error message parameters are passed to `ValidationError`](http://newforms.readthedocs.org/en/latest/validation.html#throwing-validationerror) and interpolation is done by its [`messages()` method](http://newforms.readthedocs.org/en/latest/validation_api.html#validationerror).

If you're working with an `ErrorObject` directly, the [ErrorList objects it contains have a `messages()` method](http://newforms.readthedocs.org/en/latest/validation_api.html#ErrorList#messages) which will do that for you.

This is how you can do it while sticking to the [public Error API](http://newforms.readthedocs.org/en/latest/validation_api.html#errors)

``` javascript
errs.get(field_id).messages().forEach(function(message) {
  if (label != null) {
    message = label + '. ' + message
  }
  err_messages.push(message)
```
