### ISSUE TITLE
IntegerField only passes value limits to `NumberWidget`

### ISSUE THREAD

**Issue by kevzettler** [insin/newforms#59]
https://github.com/insin/newforms/blob/react/src/fields/IntegerField.js#L58

What if i'm using a custom widget with `IntegerField` and want access minValue and MaxValue?

**Comment by insin** [comment]
Currently, you'd have to extend `IntegerField`.

Looks like we need some API for a widget to signal which Field configuration it needs access to, or otherwise access details of the Field it's rendering.
