### ISSUE TITLE
Allow to set focus on a field

### ISSUE THREAD

**Issue by Ismael** [insin/newforms#63]
For example, I have a button "Sign up!" which will show the form, but by default, it doesn't have focus on the first input. Please provide a way to focus on a particular input field.
Maybe allow to name the refs for each field?

**Comment by insin** [comment]
Adding an `autoFocus` prop to the field's widget should do this the first time it's rendered.

The new `widgetAttrs` option being discussed in #62 should provide a more convenient way to do this.

**Comment by insin** [comment]
The new Field core argument added for #62 - `widgetAttrs` - will let you add an `autoFocus` or `ref` prop to a widget in order to do this whichever ways is most appropriate for your app.
