### ISSUE TITLE
Building .11 w/ browserify

### ISSUE THREAD

**Issue by ericdfields** [insin/newforms#66]
When trying to build master w/ browserify, I get the following error:

```
Error: Cannot find module './components/FormRow' from '/Users/EricFields/Development/newforms/src'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:99:15)
```

I figured I needed a react transformer, so I tried building it with `browserify -t reactify` and got the same error.

I tried adding 'reactify' to the browserify entry in package.son:

```
  "browserify": {
    "transform": [
      "envify",
      "reactify"
    ]
  },
```

Again, same error.

If I remove all the component requires from src/newforms.js it compiles fine.

Somehow, browserify isn't taking to transforming these files. I'd really appreciate some help. Thank you!

**Comment by insin** [comment]
`src/` is treated as source, not executable.

It won't bundle directly from there because the React component modules have a `.jsx` extension but the require is `require('./components/<name>')`, which will look for `<name>.js`

If you've `npm install`ed dependencies, `gulp transpile-js` will build a usable version to `lib/`.

**Comment by ericdfields** [comment]
Thank you. I did that and hopped over to `lib/` and it looks like browserify works effortlessly now. Thank you @insin.
