### ISSUE TITLE
Using field choices raises React warning (unique key missing)

### ISSUE THREAD

**Issue by Ismael** [insin/newforms#68]
The following code produces this warning: "Each child in an array should have a unique "key" prop. Check the render method of FormRow. See http://fb.me/react-warning-keys for more information."

``` javascript
var React = require("react");
var forms = require("newforms");
var IPIN = forms.Form.extend({
    device: forms.ChoiceField({choices: ["eth0", "eth1"]}),
});
var IPINform = new IPIN();

var Thing = React.createClass({
  getInitialState: function(){
    return {form: IPINform};
  },
  render: function(){
    return (
            <form>
                <forms.RenderForm form={this.state.form} ref="ipin" />
                <button>submit</button>
            </form>
        );
  }
});
var r = React.render(<Thing/>, document.body);
```

**Comment by insin** [comment]
Must be the `<option>`s, should be easy to fix.

**Comment by Ismael** [comment]
I'd guess this is related:
" Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>."

**Comment by insin** [comment]
That one depends on facebook/react#1398 - we currently need to set `selected` manually to support server-side rendering
