### ISSUE TITLE
Wrap field name and prepend w/ string

### ISSUE THREAD

**Issue by ericdfields** [insin/newforms#70]
A common convention for form field inputs is to name each field as a sort of property to the object class we're modifying, for example `<input name="patient[first_name]">` for the _First Name_ input of my _Patient_ form. This is the default for Rails forms, and I've seen it elsewhere too.

I see that you can pass a `prefix` on the Forms class to prefix our field names — I could generate `patient-first_name` in this case — but I can't quite pull off that wrapping I'd like. Is this currently possible? Would you take a PR that makes it so if not?

**Comment by insin** [comment]
Could use a prefix format string for this similar to `autoId`, current behaviour would have it defaulting to `'{prefix}-{name}'`.

Putting that on `Form.prototype` would allow overriding when extending, or monkeypatching globally.

**Comment by ericdfields** [comment]
Passing a nested object to create an `object[attribute]` relationship also comes to mind.

```
var SignupForm = forms.Form.extend({
  patient: {
    __mixins__: [PersonForm],
    birth_date: forms.CharField({
        widget: forms.TextInput({attrs: {className: 'datepicker'}})
     })(),
     ...
  }
})
```

creates `<input name="patient[birth_date]" />`, etc…
