### ISSUE TITLE
Support Autocomplete Fields

### ISSUE THREAD

**Issue by marr** [insin/newforms#71]
I am trying to pass in an autocomplete parameter according to https://html.spec.whatwg.org/multipage/forms.html#autofill-field and I don't see it persisted through to the rendered html.

Here is the code I'm using:

```
        card_number: newforms.CharField({
            required: true,
            name: "card_number",
            label: "Card Number",
            widget: newforms.TextInput({attrs:{
                autocomplete: 'cc-number',
                placeholder: 'Card Number',
            },controlled: true})
        }),

```

**Comment by insin** [comment]
React needs camelCase attributes, so you need to use `autoComplete`: http://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes

**Comment by marr** [comment]
Thanks Johnny. I did end up seeing the warning in the console and building with the camelCased property. It seems like chrome ignores it, however. Do you know if thats a known issue with chrome in general?

**Comment by insin** [comment]
Seems like it's Chrome-only to me: http://www.html5rocks.com/en/tutorials/forms/requestautocomplete/

First I've heard of this API.
