### ISSUE TITLE
Formset input names prefixed with undefined

### ISSUE THREAD

**Issue by ericdfields** [insin/newforms#74]
I'm creating a form with FormSets and borrowing code that's in the examples. I've got the FormSet rendering and also intaking the initial data, but the name of the input is being prefixed with `undefined`. Here is what should be the relevant code:

``` javascript
var EmailAddressForm = forms.Form.extend({
  value: forms.EmailField({label: "Email Address"}),
  is_primary: forms.BooleanField({required: false})
})

var EmailAddressFormSet = forms.FormSet.extend({form: EmailAddressForm})

var Patient = React.createClass({
  getInitialState: function() {
    return {
      emailAddressForms: new EmailAddressFormSet({
        initial: this.props.data.email_addresses,
        prefix: this.prefix('email'),
        onChange: this.forceUpdate.bind(this)
      })
    }
  }, 
  prefix:function(formsetType) {
    return this.props.prefix + '-' + formsetType
  },
  renderEmailAddressForms: function() {
    return this.state.emailAddressForms.forms().map(function(form, i)  {
      return (
        <forms.RenderForm form={form} />
      )
    })
  },
  render: function() {
    console.log(this.props.data)
    return (
      <form>
        <forms.RenderForm form={PatientForm} ref="form" data={this.props.data} />
        <this.renderEmailAddressForms form={EmailAddressForm} ref="form" data={this.props.data} />
      </form>
    )
  }
})
```

My `this.props.data.email_addresses` is an array of one array — `[['testing@gmail.com', true]] — and so as expected I get one set of fields with the initial data and one extra set of fields for a new email.

The inputs that get generated look like:

``` javascript
<input type="email" name="undefined-email-0-value" class="form-control" id="id_undefined-email-0-value" value="testing@gmail.com" data-reactid=".24ehrn5scn4.1:0.$undefined-email-0-value.0.$undefined-email-0-value">
```

What param am I failing to pass that causes that undefined name?

**Comment by insin** [comment]
Are you passing a `prefix` prop to your `Patient` component when rendering it? If not, your component's `prefix()` method would be generating '`undefined-email'` as the formset's `prefix` option.

I take it this is pared down from something too big to show? I would have expected the initial data for the FormSet to look more like this in order to work:

``` javascript
[{value: 'testing@gmail.com', is_primary: true}]
```

**Comment by ericdfields** [comment]
Probably not. Thank you. Generally always pass a prefix?

## 

Eric

**Comment by insin** [comment]
You only _need_ prefixes if you're rendering the same Form multiple times, or rendering multiple Forms/FormSets which share some of the same field names, just to make sure generated `name` and `id` arrtibutes don't clash.

Probably a good idea to use them all the time in more complex scenarios, though, in case you forget to do it later if a clash is introduced.

**Comment by ericdfields** [comment]
``` javascript
[{value: 'testing@gmail.com', is_primary: true}]
```

was indeed my initial data. I misread/typed.

Passing prefix into this.props worked. Thank you.
