### ISSUE TITLE
Support Autofill with initial field values

### ISSUE THREAD

**Issue by marr** [insin/newforms#77]
Hi, I am starting to understand the api _a little_ and hope to use autofill from my browser for a cc component I'm building.  I set `initial: 1` on my cc month field, and when I chose a cc number from autofill, the 1 doesn't get populated with the saved month due to the `initial` setting. I have tried using `controlled: true` on both the `field` and `widgetAttrs` properties. Please let me know if you have a way to set the initial value of a field, but also support autofill from the browser. Thanks in advance!
Here's an example of the `Form` I'm using: https://gist.github.com/811ebb26ac7642bee0c0

**Comment by insin** [comment]
Have you tried autofill functionality with a plain old React `<input/>` to see if it fires `onChange` events as expected?

I can see an open React issue - facebook/react#1159 - related to browser auto-completion not firing `onChange` events, just not sure if it's the same story for autofill functionality.

The `onChange` handler that newforms adds to each field's rendered widget should already handle this - any initial data you pass gets copied to `form.data` and the `onChange` handler should be updating `form.data` when input is taken.

**Comment by marr** [comment]
Thanks insin- don't close this quite yet. I still want to spend a bit to find out if those onChange do fire on inputs when autofilling from browser.

**Comment by marr** [comment]
I confirmed that the inputs do fire onChange when receiving the autoFill values. 
As a workaround for the initial values not being overwritten with the new autofill values, I moved the inputs to ChoiceInputs. The initial property with those _does_ get changed by the browser (Chrome).
I haven't tested with other browsers and can point you to an example of this behavior if if you'd like.
